version: '3.3'
services:
  api:
    image: shopitify-api:latest
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - ${APP_PORT}:${APP_PORT}
    env_file:
      - .env
    environment:
      - WS_DB_HOST=mongodb
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4.4.6
    restart: always
    env_file:
      - .env
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
volumes:
  mongodb_data_container:
